version: '3.4'

services:
  webapp:
    build:
      context: ..
      dockerfile: FruitShop/Dockerfile
    ports:
      - "7189:7189"
      - "5173:5173"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
