version: '3.4'

services:
  webapp:
    image: fruitshop
    ports:
      - "1337:1337"
      - "1337:1338"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:1337
